artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://universe.roboflow.com/ds/xVFScOg5j2?key=93Tq5paN8Z
  local_data: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/data


# timy-dset "https://universe.roboflow.com/ds/xVFScOg5j2?key=93Tq5paN8Z"
# E waste dataset "https://universe.roboflow.com/ds/i02h52wl6q?key=ZM0MEFLZ5R"
# COCO data     "https://public.roboflow.com/ds/fYqIOuhVKK?key=sAOM4f2h70"

data_validation:
  current_dset: artifacts/data_ingestion/data         #replace data with the name of the subset if creating one
  data_val_dir: artifacts/data_validation
  data_val_status: artifacts/data_validation/status.txt
  data_val_req: 
    - train
    - valid
    - data.yaml


train_log_config:  
  model: yolov8n.pt # choices="yolov8n","yolov8s","yolov8m","yolov8l","yolov8x"
  save_path: artifacts/trained_models
  mlflow_uri: http://127.0.0.1:5000
  experiment_name: v8nOPS
  model_name: yolov8ndet


#new custom dataset
custom_dataset:
  base_Data_path: artifacts/data_ingestion/data
  classes: []
  new_data_path: artifacts/data_ingestion
  dataset_name: version1

param:
  optimizer: SGD # other choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
  lr0: 0.03       # learning rate 
  save_period: -1
  batch: 24
  epochs: 1
  resume: False
  seed: 0
  imgsz: 640 

# evaluation:
#   path_of_model: artifacts/trained_model/Trainedv8.pt
#   trainig_data: artifacts/data_ingestion/data
#   mlflow_uri: https://dagshub.com/Arvindnbr/MLOPs.mlflow