artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://universe.roboflow.com/ds/xVFScOg5j2?key=93Tq5paN8Z
  local_data: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/data


# timy-dset "https://universe.roboflow.com/ds/xVFScOg5j2?key=93Tq5paN8Z"
# E waste dataset "https://universe.roboflow.com/ds/i02h52wl6q?key=ZM0MEFLZ5R"
# COCO data     "https://public.roboflow.com/ds/fYqIOuhVKK?key=sAOM4f2h70"

data_validation:
  data_val_dir: artifacts/data_validation
  data_val_status: artifacts/data_validation/status.txt
  data_val_req: 
    - train
    - valid
    - data.yaml


training_params:  
  model: yolov8n.pt # choices="yolov8n","yolov8s","yolov8m","yolov8l","yolov8x"
  save_path: artifacts/trained_models
  epochs: 1
  batch: 5
  imgsz: 640

mlflow:
  mlflow_uri: http://127.0.0.1:8080
  experiment_name: v8OPS
  model_name: yolov8det


# evaluation:
#   path_of_model: artifacts/trained_model/Trainedv8.pt
#   trainig_data: artifacts/data_ingestion/data
#   mlflow_uri: https://dagshub.com/Arvindnbr/MLOPs.mlflow